repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3
      args: [routing_packager_app, tests]
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1  # pick a git hash / tag to point to
  hooks:
    - id: flake8
