services:
  postgres:
    image: kartoza/postgis:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASS: admin
      POSTGRES_DB: gis_test
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432:5432
  redis:
    image: redis:6.2
    ports:
      - 6379:6379
