[tool.poetry]
name = "kadas-routing-http"
version = "0.1.0"
description = "Backend to generate Valhalla routing tiles in a job queue."
authors = ["Nils Nolde <nils@gis-ops.com>"]
license = "MIT"
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = "^3.6.1"
flask = "^1.1.2"
flask-sqlalchemy = "^2.4.4"
psycopg2-binary = "^2.8.5"
flask-cors = "^3.0.8"
GeoAlchemy2 = "^0.8.4"
flask-migrate = "^2.5.3"
wheel = "^0.35.1"
python-dotenv = "^0.14.0"
flask-restx = "^0.2.0"
requests = "^2.24.0"
sqlalchemy-utils = "^0.36.8"
passlib = "^1.7.2"
Flask-HTTPAuth = "^4.1.0"
shapely = "^1.7.1"
docker = "^4.3.1"
gunicorn = "^20.0.4"
gevent = "^20.6.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pre-commit = "^2.6.0"
yapf = "^0.30.0"
coverage = "^5.2.1"
coveralls = "^2.1.2"
tox = "^3.19.0"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
