[tool.poetry]
name = "routing-graph-packager"
version = "1.0.0b"
description = "Backend to generate packages of routing graphs for FOSS routing engines in a job queue."
authors = ["Nils Nolde <nils@gis-ops.com>"]
license = "MIT"
packages = [
    { include = "routing_packager_app" }
]

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = "^1.4.34"
GeoAlchemy2 = "^0.11.1"
wheel = "^0.37.1"
python-dotenv = "^0.20.0"
requests = "^2.27.1"
sqlalchemy-utils = "^0.38.2"
passlib = "^1.7.4"
shapely = "^1.8.1"
gunicorn = "^20.1.0"
gevent = "^21.12.0"
pyproj = "^3.3.0"
psycopg2-binary = "^2.9.3"
fastapi = "^0.85.1"
sqlmodel = "^0.0.8"
arq = "^0.25.0"
uvicorn = "^0.20.0"
pydantic = {extras = ["email"], version = "^1.10.2"}
osmium = "^3.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-asyncio = "^0.20.3"
pytest-cov = "^3.0.0"
pytest-httpserver = "^1.0.6"
pre-commit = "^2.17.0"
coverage = "^6.3.2"
coveralls = "^3.3.1"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 105
exclude = '''
/(
    \.git
  | \.venv
  | dist
  | build
)/
'''
