class JobFields:
    BBOX = 'bbox'
    INTERVAL = 'interval'
    PROVIDER = 'provider'
    ROUTER = 'router'
    DESCRIPTION = 'description'
    NAME = 'name'
    ID = 'id'
    RQ_ID = 'job_id'
    COMPRESSION = 'compression'
    CONTAINER_ID = 'container_id'
    STATUS = 'status'
    USER_ID = 'user_id'
    LAST_RAN = 'last_ran'
    PATH = 'path'
