class JobFields:
    BBOX = 'bbox'
    SCHEDULE = 'schedule'
    PROVIDER = 'provider'
    ROUTER = 'router'
    DESCRIPTION = 'description'
    NAME = 'name'
    ID = 'id'
    CONTAINER_ID = 'container_id'
    STATUS = 'status'
    USER_ID = 'user_id'
