name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        python_version: [3.7, 3.8]
    services:
      postgres:
        image: kartoza/postgis:12.1
        env:
          POSTGRES_USER: admin
          POSTGRES_PASS: admin
          POSTGRES_DB: gis_test
          ALLOW_IP_RANGE: 0.0.0.0/0
        options: >-
         --health-cmd pg_isready
         --health-interval 10s
         --health-timeout 5s
         --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:6.0
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
#     From https://github.com/python-poetry/poetry/actions
    - name: Get full python version
      id: full-python-version
      run: |
        echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info[:3]))")
    - name: Install and set up Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry config virtualenvs.in-project true
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install
    - name: Pull image(s)
      run: |
        sudo docker pull gisops/valhalla:latest
        sudo docker pull graphhopper/graphhopper:latest
        sudo docker pull openrouteservice/openrouteservice:latest
        sudo docker pull osrm/osrm-backend:latest
    - name: Install osmium
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
        sudo add-apt-repository 'deb http://ftp.debian.org/debian sid main'
        sudo apt-get update
        sudo apt-get install -y -qq osmium-tool
        echo $(osmium --version)
    - name: yapf linting
      run: |
        source .venv/bin/activate
        yapf -r -vv --diff -p tests routing_packager_app config.py http_app.py gunicorn.py
    - name: pytest
      run: |
        source .venv/bin/activate
        sudo python -m smtpd -n -c DebuggingServer localhost:1025 &
        sudo docker volume create routing-packager_packages --driver local --opt type=none --opt device=$PWD --opt o=bind
        pytest --cov=routing_packager_app -ignore=tests/test_tasks.py
    - name: coveralls
      run: |
        source .venv/bin/activate
        coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}